chore : update pre-check for UpdateDefaultTranslations before docker build
Signed-off-by: Abhijay007 <Abhijay007j@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -45,14 +45,21 @@ jobs:
       - run:
           command: |
             curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/btcpayserver/btcpayserver-doc/dispatches --data '{"event_type": "build_docs"}'
-  check_translations:
+  release_checks:
     machine:
       image: ubuntu-2004:2024.11.1
     steps:
       - checkout
       - run:
           command: |
-            cd .circleci && ./check-translations.sh
+            cd .circleci && ./run-tests.sh "PreReleaseCheck=PreReleaseCheck"
+      - run:
+          name: Check if translations are up to date
+          command: |
+            if ! git diff --exit-code BTCPayServer/Services/Translations.Default.cs; then
+              echo "ERROR: Translations.Default.cs is out of date! Please run UpdateDefaultTranslations test before building docker images."
+              exit 1
+            fi
   # publish jobs require $DOCKERHUB_REPO, $DOCKERHUB_USER, $DOCKERHUB_PASS defined
   docker:
     docker:
@@ -91,7 +98,7 @@ workflows:
             # only act on version tags
             tags:
               only: /(v[1-9]+(\.[0-9]+)*(-[a-z0-9-]+)?)|(v[a-z0-9-]+)/
-      - check_translations:
+      - release_checks:
           filters:
             branches:
               ignore: /.*/
@@ -99,7 +106,7 @@ workflows:
               only: /(v[1-9]+(\.[0-9]+)*(-[a-z0-9-]+)?)|(v[a-z0-9-]+)/
       - docker:
           requires:
-            - check_translations
+            - release_checks
           filters:
             # ignore any commit on any branch by default
             branches:
